### ISSUE TITLE
Allow adding time entries in the future if the entry is a leave/holiday

### ISSUE THREAD

**Issue by gsakhardande** [anshulbajpai/minutedock#86]
I have observed that when people (including me) go on holidays in the last week of a month and are probably arriving back at office in the next month, they can't fill entries for the remaining days in current month.

Is it possible to allow people to fill leaves in advance (at least for the current month), so that the client billing won't be blocked. As far as I feel, only leaves should be allowed to filled for the future, otherwise, people will fill all entries for office in advance leading to other ambiguities.

**Comment by anshulbajpai** [comment]
Have you tried this on original minutedock ? I don't think they allow
future entries.

**Comment by gsakhardande** [comment]
Hmm.. OK. Limitation due to minutedock.
